channels:
  - label: "やんちゃクラブ"
    slug: "yancya-club"
    feed_url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCn3T1nqjGuC40r_agfyF0Ag"
    format: "video"
  - label: "コテンラジオ"
    slug: "coten-radio"
    feed_url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCr5zQB5J5DJqZfar_WyWFAw"
    format: "video"
  - label: "モンゴルナイトフィーバー"
    slug: "mongol-night-fever"
    feed_url: "https://www.youtube.com/feeds/videos.xml?channel_id=UCWzXsL9T4nAskfsf_9aXFaQ"
    format: "audio"
storage:
  type: "r2"
  bucket: "your-bucket-name"
  account_id: "your-account-id"
  access_key_id: "your-access-key-id"
  secret_access_key: "your-secret-access-key"
  public_url: "https://your-public-url.r2.dev" 
